[package]
name = 'move-learn'
version = '1.0.0'

[dependencies]
AptosFramework = { local = "/mnt/e/ProgramForUbuntu/aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "/mnt/e/ProgramForUbuntu/aptos-core/aptos-move/framework/aptos-stdlib" }


[addresses]
Sender='0x12'